# Generated by Django 4.0.3 on 2022-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='max_session',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
